# File: .github/workflows/repo-sync.yml

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "Ruze-alt/privacy"
        source_branch: "main"
        destination_repo: "svl-at-asu/CODAP-privacy-plugin"
        destination_branch: "main"
        github_token: ${{ secrets.PAT }}
